# Generated by Django 4.0.3 on 2023-01-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_pics'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_pics'),
        ),
    ]
