# Generated by Django 4.0.3 on 2023-01-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistproduct',
            old_name='Wishlist',
            new_name='wishlist',
        ),
    ]
